config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  resources :categories, only: %i[index show new create destroy] do
    resources :transacctions, only: %i[new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :category
  belongs_to :transacction
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :icon_url, presence: true
  # associations
  belongs_to :author, class_name: 'User'
  has_many :categorizations, dependent: :destroy
  has_many :transacctions, through: :categorizations
end

app/models/transacction.rb
class Transacction < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true
  # associations
  belongs_to :author, class_name: 'User'
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, allow_blank: false
  # associations
  has_many :transactions, dependent: :destroy, foreign_key: 'author_id'
  has_many :categories, dependent: :destroy, foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @user = current_user
    @categories = @user.categories
  end

  def show
    @category = Category.find(params[:id])
    trans = @category.transacctions
    @transacctions = trans.order(created_at: :desc)
  end

  # GET /foods/new
  def new
    @category = Category.new
  end

  # POST /foods or /foods.json
  def create
    @author = current_user
    @category = Category.new(category_params)
    @category.author = @author

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @Category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon_url, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/controllers/transacctions_controller.rb
class TransacctionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]
  # GET /transacction/new
  def new
    @transacction = Transacction.new

    @category = Category.find(params[:category_id])
  end

  # POST /transacction or /transacction.json
  def create
    @author = current_user
    @transaction = Transacction.new(transacction_params)
    @transaction.author = @author
    @transaction.category_ids = params[:transacction][:category_ids]

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to categories_url, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transacction
    @transaction = Transacction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transacction_params
    params.require(:transacction).permit(:name, :amount, :category_ids, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="min-vh-100 d-flex flex-column justify-content-between bg-lightgray">
  <div>
    <%= render "shared/nav_bar"%>
    <%= render "shared/messages"%>
    <% @categories.each do |item|%>
      <%= link_to category_path(item), class: 'text-decoration-none  ' do%>
        <div class="row align-items-center m-1 my-2 p-1 bg-white">
          <%= image_tag(item.icon_url, class: 'img-fluid col-4')%>
          <p class= "col-4 text-center text-black-50 "><%= item.name%></p>
          <p class= "col-4 text-center text-dark fbold"><%=number_to_currency(item.transacctions.sum(:amount))%></p>
        </div>
      <%end%>
    <%end%>
  </div>

  <%= link_to new_category_path, class:'btn bg-green green w-100 rounded-0 d-flex justify-content-center' do %>
    <p class="text-white border my-2 w-100 p-3">Add category</p>
  <%end%>
</div>

app/views/categories/new.html.erb
<div>
<%= form_with model: @category, url: categories_path do |f|%>

<div class="d-flex bg-blue align-items-center justify-content-between w-100 p-3">
  <%= link_to :back do %>
    <i class="fa-solid fa-arrow-left text-white"></i>
  <%end %>
  <h2 class="text-white ms-4">Add category</h2>
  <div class="">
    <%= f.submit "Next", class: 'w-100 p-3 bg-blue login rounded-0 text-white border-0' %>
  </div>
</div>
<%= render "shared/messages"%>
<div class="mt-3">
  <%= f.text_field :name, placeholder: 'Name', class: 'form-control rounded-0 p-3' %>
  <%= f.text_field :icon_url, placeholder: 'Icon url',class: 'form-control rounded-0 p-3' %>
</div>

<%end%>
<% if flash[:error] %>
    <div><%= flash[:error] %></div>
<% end %>
</div>
</div>

app/views/categories/show.html.erb
<div class="min-vh-100 d-flex flex-column justify-content-between bg-lightgray">
  <div>
    <%= render "shared/nav_bar"%>
    <%= render "shared/messages"%>
    <div class="d-flex justify-content-between p-1 bg-white mb-4">
      <p class= "text-black-50"><%=@category.name%> category expenses:</p>
      <p class= "text-dark fbold"><%= number_to_currency(@transacctions.sum(:amount))%></p>
    </div>

    <% @transacctions.each do |item|%>
        <div class="d-flex justify-content-between m-2 p-2 bg-white">
          <div>
            <p class= "text-black-50 m-0"><%= item.name%></p>
            <p class= "text-black-50 m-0 mt-3 fsize80"><%= item.created_at.strftime("%d %b %y")%></p>
          </div>
          <p class= "text-center text-dark fbold"><%= number_to_currency(item.amount)%></p>
        </div>
    <%end%>
  </div>
  <%= link_to new_category_transacction_path(@category), class:'btn bg-green green w-100 rounded-0 d-flex justify-content-center' do %>
    <p class="text-white border my-2 w-100 p-3">Add transaction</p>
  <%end%>
</div>

app/views/home/index.html.erb
<div class="d-flex flex-column vh-100 align-items-center">
  <div class="flex-grow-1 d-flex justify-content-center align-items-center">
   <h1 class="">Track Your Buck</h1>
  </div>

  <div class="d-flex flex-column w-100 mb-4 ">
      <%= link_to "Log in", new_user_session_path, class:'login text-decoration-none text-center bg-blue text-white rounded-0 mx-2 py-3' %>
      <%= link_to "Sign up", new_user_registration_path, class:'btn btn-secondary rounded-0 mx-2 py-3' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-vh-100">
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/4b8fe0d7fd.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_messages.html.erb
<% if notice.present?%>
    <p class="notice"><%= notice %></p>
    <%end%>
    <% if alert.present?%>
    <p class="alert"><%= alert %></p>
    <%end%>

app/views/shared/_nav_bar.html.erb
<div class="d-flex bg-blue align-items-center justify-content-between w-100 p-3">
  <% if  params[:id].present? %>
    <%= link_to categories_path do %>
      <i class="fa-solid fa-arrow-left text-white"></i>
    <%end %>
  <%else%>
    <%= link_to :back do %>
      <i class="fa-solid fa-arrow-left text-white"></i>
    <%end %>
    <%end%>
    <%p params%>
    <% if params[:action] == 'show'%>
      <h2 class="text-white ms-4">transactions</h2>
    <% else%>
    <h2 class="text-white ms-4"><%= params[:controller]%></h2>
    <%end%>
    <%= button_to "Log out", destroy_user_session_path, class: "btn bg-blue login text-white", method: :delete, data: { turbo: false } %>
  </div>

app/views/transacctions/new.html.erb
<div class="min-vh-100 bg-lightgray">
  <%= form_with model: @transacction, url: category_transacctions_path do |f|%>
    <div class="d-flex bg-blue align-items-center justify-content-between w-100 p-3">
      <%= link_to :back do %>
        <i class="fa-solid fa-arrow-left text-white"></i>
      <%end %>
      <h2 class="text-white ms-4">Add transaction</h2>
      <div class="">
        <%= f.submit "Next", class: 'w-100 p-3 bg-blue login rounded-0 text-white border-0' %>
      </div>
    </div>
    <%= render "shared/messages"%>
    <div class="mt-3">
      <%= f.text_field :name, placeholder: 'Name', class: 'form-control rounded-0 p-3' %>
      <%= f.text_field :amount, placeholder: 'Amount', class: 'form-control rounded-0 p-3' %>
    </div>
    <div class="m-3" >
      <p class="m-0 text-black-50">Select category/categories</p>
      <% Category.where(author_id: current_user.id).each do |item|%>
      <%p params[:category_id].to_i%>
        <% if item.id == params[:category_id].to_i%>
          <%= check_box_tag "transacction[category_ids][]", item.id, true%>
        <%else%>
          <%= check_box_tag "transacction[category_ids][]", item.id%>
        <%end%>
        <%= item.name%><br>
      <%end%>
    </div>
  <%end%>
  <% if flash[:error] %>
      <div><%= flash[:error] %></div>
  <% end %>
</div>